feat: add filesystem selection

diff --git a/install-scripts/arch-server b/install-scripts/arch-server
--- a/install-scripts/arch-server
+++ b/install-scripts/arch-server
@@ -3,7 +3,7 @@ set -e
 
 # Print an ASCII art logo
 logo() {
-printf "\033[35m_____________________________________________ 
+printf "\033[36m_____________________________________________ 
      __              __        _  _        
     /  )        /   /  )      // //        
    /--/ __  _. /_  /  / __.  // // __.  _, 
@@ -16,18 +16,18 @@ _____________________________________________
 _____________________________________________\033[0m\n"
 }
 
-# Make sure the script is run from an Arch Linux ISO environment
-verify_iso() {
-    if [ ! -e /run/archiso/bootmnt/arch/x86_64/airootfs.sfs ]; then
-        printf "\033[31mERROR: This script must be run from an Arch Linux ISO environment.\033[0m\n"
-        exit 1
-    fi
-}
-
 # Make sure the script is run as root
 verify_root() {
     if [ "$(id -u)" -ne 0 ]; then
         printf "\033[31mERROR: This script must be run as root.\033[0m\n"
+        exit 1
+    fi
+}
+
+# Make sure the script is run from an Arch Linux ISO environment
+verify_iso() {
+    if [ ! -e /run/archiso/bootmnt/arch/x86_64/airootfs.sfs ]; then
+        printf "\033[31mERROR: This script must be run from an Arch Linux ISO environment.\033[0m\n"
         exit 1
     fi
 }
@@ -44,21 +44,64 @@ verify_pacman() {
     fi
 }
 
+# Group all verification functions
+verify_all() {
+    verify_root
+    verify_iso
+    verify_pacman
+}
+
 # Detect if the system is running in UEFI or BIOS mode
-verify_boot_mode() {
+boot_mode() {
     if [ -f /sys/firmware/efi/fw_platform_size ]; then
-        printf "\033[1;32mSystem will be installed in UEFI mode.\033[0m\n"
-        BOOT_MODE="UEFI"
+        printf "\n\033[1;32m>> System will be installed in UEFI mode.\033[0m\n"
+        BOOT=UEFI
     else
-        printf "\033[1;33mSystem will be installed in BIOS mode. UEFI is recommended for better support.\033[0m\n"
-        BOOT_MODE="BIOS"
+        printf "\n\033[1;32m>> System will be installed in BIOS mode.\033[0m\n"
+        BOOT=BIOS
     fi
 }
 
-# Group all verification functions
-verify_all() {
-    verify_iso
-    verify_root
-    verify_pacman
-    verify_boot_mode
+filesystem() {
+    while :; do
+        printf "\033[36m_____________________________________________
+
+             Choose a Filesystem
+_____________________________________________ 
+
+  [1] ext4: Recommended for most users, 
+  stable and widely supported.
+
+  [2] btrfs: Advanced filesystem with 
+  features like snapshots and compression.
+
+  [3] xfs: High-performance filesystem 
+  suitable for large files and databases.
+_____________________________________________
+
+Make your choice (1-3), default is ext4: \033[0m"
+
+        read -r fs_choice
+
+        case $fs_choice in
+            1|"" )
+                printf "\033[1;32m>> Filesystem set to ext4\033[0m\n"
+                FS=ext4
+                break
+                ;;
+            2 )
+                printf "\033[1;32m>> Filesystem set to btrfs\033[0m\n"
+                FS=btrfs
+                break
+                ;;
+            3 )
+                printf "\033[1;32m>> Filesystem set to xfs\033[0m\n"
+                FS=xfs
+                break
+                ;;
+            * )
+                printf "\033[33m>> Invalid option, please try again\033[0m\n"
+                ;;
+        esac
+    done
 }
